feature(schemas): coded values mapping
MapColonies/external-to-osm-tag-mapping pull request #110
Opened 2021-11-15 08:27 UTC by vitaligi

adds the ability to map tag values to a coded value based on a mapping in remote repo (redis)

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2021-11-16 08:41 UTC, CptSchnitz requested changes

2021-11-16 08:41 UTC, CptSchnitz commented on src/common/db.ts
>      throw new Error('Redis connection failed');
i dont think its necessary to catch the error here, please check and remove if so.

2021-11-16 08:41 UTC, CptSchnitz commented on src/schema/DAL/domainFieldsRepository.ts
> +  getFields: ((fields: string[], key: string | undefined) => Promise<string[]>) | ((fields: string[]) => Promise<string[]>);
if key is constant, dont ask for it on every function call.

2021-11-16 08:41 UTC, CptSchnitz commented on src/schema/DAL/redisManager.ts
> +      res = key !== undefined ? await this.redis.hmget(key, fields) : await this.redis.mget(fields);
change it to multiline if please.

2021-11-16 08:41 UTC, CptSchnitz commented on src/schema/models/schemaManager.ts
> +        [domainFieldsKeys[index].split(':')[0]]: codedValue,
revert back to adding _domain.

2021-11-16 08:41 UTC, CptSchnitz commented on src/schema/models/schemaManager.ts
> +        explode = Object.entries(explode).reduce((acc, [key, value]) => {
only from line 156 it should be called exploded

2021-11-28 14:34 UTC, melancholiai commented on src/schema/models/schemaManager.ts
> +        [domainFieldsKeys[index].split(':')[0]]: codedValue,
done.

2021-12-01 11:51 UTC, merged

2021-12-06 09:23 UTC, vitaligi commented
closes #101