chore: initial project
MapColonies/external-to-osm-tag-mapping pull request #3
Opened 2020-12-14 12:12 UTC by galta95

2020-12-15 06:59 UTC, syncush requested changes

2020-12-15 06:59 UTC, syncush commented on Dockerfile
> +RUN chmod +x /confd/confd
lets drop confd

2020-12-15 06:59 UTC, syncush commented on Dockerfile
> +HEALTHCHECK CMD wget http://127.0.0.1:${SERVER_PORT}/liveness -O /dev/null || exit 1
drop

2020-12-15 06:59 UTC, syncush commented on commitlint.config.js
> +module.exports = { extends: ['@commitlint/config-conventional'] };
let's add the relevant scopes

2020-12-16 12:16 UTC, galta95 commented on Dockerfile
> +RUN chmod +x /confd/confd
done

2020-12-16 12:16 UTC, galta95 commented on Dockerfile
> +HEALTHCHECK CMD wget http://127.0.0.1:${SERVER_PORT}/liveness -O /dev/null || exit 1
done

2020-12-16 12:16 UTC, galta95 commented on commitlint.config.js
> +module.exports = { extends: ['@commitlint/config-conventional'] };
done

2020-12-16 13:48 UTC, syncush approved these changes

2020-12-20 11:34 UTC, merged