feat: add liveness probe
MapColonies/external-to-osm-tag-mapping pull request #93
Opened 2021-09-12 11:08 UTC by syncush

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2021-09-13 07:35 UTC, CptSchnitz requested changes
Right now the redis connection retries to connect on failure indefinitely.
While this is happening the liveness check takes a long time to return.
We should choose what is the desired behaviour.

2021-09-13 07:35 UTC, CptSchnitz commented on src/common/constants.ts
> +  HEALTHCHECK = 'healthcheck',
use symbol instead

2021-09-13 10:48 UTC, syncush commented on src/common/constants.ts
> +  HEALTHCHECK = 'healthcheck',
done

2021-10-10 07:11 UTC, CptSchnitz approved these changes

2021-10-10 07:21 UTC, merged